#pragma once

/* Base version of the PiouAutoLoader (PIOU) content.
 * Bump this when the autoloader frontend changes — it triggers the app-cache
 * update and also marks the matching PIOU installer build. */
#define PIOU_VERSION "0.5.4"

/* Full build version (stable: <base>, dev: <base>-dev-<hash|timestamp>),
 * generated by tools/gen_version.py — see include/piou_version.h */
#include "piou_version.h"

/* Network Settings — arbitrary port, chosen to avoid colliding with other
 * homebrew HTTP servers (must match the deeplink in assets/param.json.template) */
#define PIOU_PORT 18181

/* Title ID of the installed homescreen app ("PiouAutoLoader") */
#define PIOU_TITLE_ID "PIOU00001"

/* Process identity — used to kill stale installer instances on startup */
#define PIOU_THREAD_NAME "piou.elf"

/* Safety limits for the temporary installer process.
 *
 * PIOU_KILL_RETRIES bounds the startup SIGKILL loop: a previous instance that
 * refuses to die must never wedge this one forever.
 * PIOU_MAX_LIFETIME_SEC bounds how long the HTTP server may run. The installer
 * only lives until the browser finishes caching (/install) or asks it to exit
 * (/exit); if the browser tab is closed first, nothing else would ever stop
 * it, leaving port PIOU_PORT held by a zombie. The cap is generous
 * (10 minutes) so a slow first-time cache on a busy console still completes. */
#define PIOU_KILL_RETRIES 10
#define PIOU_MAX_LIFETIME_SEC 600

/* Routes */
#define ROUTE_INDEX "/"
#define ROUTE_INDEX_HTML "/index.html"
#define ROUTE_CACHE_MANIFEST "/cache.appcache"
#define ROUTE_INSTALL "/install"
#define ROUTE_VERSION "/version"
#define ROUTE_CLEAR_WEBKIT_DATA "/clear-webkit-data"
#define ROUTE_EXIT "/exit"

/* Logging (implementation in log.c) */
void piou_log(const char *fmt, ...);
size_t piou_wait_logs(size_t *pos, char *out_buf, size_t max_len);
void piou_log_wakeup(void);

/* Notifications (declared in notification.h) */
#include "notification.h"
